/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Label;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author jesfrin
 */
public class LienzoInternalF extends javax.swing.JInternalFrame {

    /**
     * Creates new form LienzoInternalF
     */
    public LienzoInternalF() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        //bujarRectangulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miPanel1 = new javax.swing.JPanel();

        miPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout miPanel1Layout = new javax.swing.GroupLayout(miPanel1);
        miPanel1.setLayout(miPanel1Layout);
        miPanel1Layout.setHorizontalGroup(
            miPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        miPanel1Layout.setVerticalGroup(
            miPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel miPanel1;
    // End of variables declaration//GEN-END:variables
    public void dibujarRectangulo() {

    }
    
    public void limpiarLienzo(Color color){
        Label label = new Label();
        label.setBounds(0, 0, 700, 400);
        this.miPanel1.add(label);
        this.miPanel1.remove(label);
    }

}
