
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.analizadorInstrucciones;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ST = 40;
  public static final int NUMERO = 5;
  public static final int POSITION_XY = 31;
  public static final int BACKWARD = 15;
  public static final int POR = 9;
  public static final int POS_XY = 32;
  public static final int CORCHETE_CERRADO = 47;
  public static final int PD = 26;
  public static final int REPEAT = 45;
  public static final int FORWARD = 13;
  public static final int PEN_DOWN = 25;
  public static final int CODIGO_COLOR = 30;
  public static final int PARENTESIS_ABIERTO = 11;
  public static final int TO_ERASE = 41;
  public static final int TO_DRAW = 43;
  public static final int CS = 22;
  public static final int CR = 28;
  public static final int IDENTIFICADOR = 3;
  public static final int IGUAL = 6;
  public static final int LT = 20;
  public static final int RT = 18;
  public static final int SHOW_TURTLE = 39;
  public static final int DIV = 10;
  public static final int FD = 14;
  public static final int LEFT = 19;
  public static final int CORCHETE_ABIERTO = 46;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 48;
  public static final int COMENTARIO = 4;
  public static final int MENOS = 8;
  public static final int HT = 38;
  public static final int ERROR_LEXICO = 2;
  public static final int COLOR = 29;
  public static final int BK = 16;
  public static final int HIDE_TURTLE = 37;
  public static final int POSITION_Y = 35;
  public static final int POSITION_X = 33;
  public static final int TO_CENTER = 27;
  public static final int PEN_UP = 23;
  public static final int TE = 42;
  public static final int PARENTESIS_CERRADO = 12;
  public static final int TD = 44;
  public static final int CLEARS = 21;
  public static final int RIGHT = 17;
  public static final int POS_Y = 36;
  public static final int MAS = 7;
  public static final int POS_X = 34;
  public static final int PU = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR_LEXICO",
  "IDENTIFICADOR",
  "COMENTARIO",
  "NUMERO",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "FORWARD",
  "FD",
  "BACKWARD",
  "BK",
  "RIGHT",
  "RT",
  "LEFT",
  "LT",
  "CLEARS",
  "CS",
  "PEN_UP",
  "PU",
  "PEN_DOWN",
  "PD",
  "TO_CENTER",
  "CR",
  "COLOR",
  "CODIGO_COLOR",
  "POSITION_XY",
  "POS_XY",
  "POSITION_X",
  "POS_X",
  "POSITION_Y",
  "POS_Y",
  "HIDE_TURTLE",
  "HT",
  "SHOW_TURTLE",
  "ST",
  "TO_ERASE",
  "TE",
  "TO_DRAW",
  "TD",
  "REPEAT",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "COMA"
  };
}

